title: "EMB Engineering's Blog"
author: "Emmanuel Morales"
username: "@embengineering"
email: "contact@embengineering.com"
domain: "embengineering.com"
description: A blog of ideas and thoughts about Front-End development, technology and more.
url: "http://blog.embengineering.com" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: /posts/:title
redcarpet:
    extensions: [with_toc_data]
future: true
poole:
    word_separator: "-"
include: [".well-known"]
sass:
    sass_dir: _sass
    sourcemap: true

# Build settings
markdown: kramdown

# Note: include drafts by using "jekyll serve --drafts" command.

# Custom variables
profile_thumbnail: "http://blog.embengineering.com/assets/intro-bg.jpg"
excerpt_separator: <!--more-->
