title: "EMB Engineering's Blog"
description: A blog of ideas and thoughts about Front-End development, technology and more.
url: "https://blog.embengineering.com" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: /posts/:title
redcarpet:
    extensions: [with_toc_data]
future: true
poole:
    word_separator: "-"
include: [".well-known"]
sass:
    sass_dir: _sass
    sourcemap: true

# Build settings
markdown: kramdown

# Note: include drafts by using "jekyll serve --drafts" command.

# Custom variables
profile_thumbnail: "https://avatars0.githubusercontent.com/u/1769860?v=3&s=460"
excerpt_separator: <!--more-->
